config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  get 'sessions/new'

  get '/twepics', to: 'twepics#index'
  resources :twepics do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :twepic
end

app/models/twepic.rb
class Twepic < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 140 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password_digest, presence: true, length: { minimum: 6 }
  has_many :twepics
  has_many :favorites, dependent: :destroy
  has_many :favorite_twepics, through: :favorites, source: :twepic
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(twepic_id: params[:twepic_id])
    redirect_to twepics_url, notice: "#{favorite.twepic.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to twepics_url, notice: "#{favorite.twepic.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/twepics_controller.rb
class TwepicsController < ApplicationController
  before_action :set_twepic, only: [:show, :edit, :update, :destroy]
  before_action :login, only: [:new, :edit, :show, :destroy]

  def index
    @twepics = Twepic.all
  end

  def new
    if params[:back]
      @twepic = Twepic.new(twepic_params)
    else
      @twepic = Twepic.new
    end
  end

  def create
    @twepic = Twepic.create(twepic_params)
    @twepic.user_id = current_user.id
    if @twepic.save
      TwepicMailer.twepic_mail(@twepic).deliver
      redirect_to twepics_path, notice: "投稿しました！"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(twepic_id: @twepic.id)
  end

  def edit
  end

  def update
    if @twepic.update(twepic_params)
      redirect_to twepics_path, notice: "編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @twepic.destroy
    redirect_to twepics_path, notice:"削除しました！"
  end

  def confirm
    @twepic = Twepic.new(twepic_params)
    @twepic.user_id = current_user.id
    render :new if @twepic.invalid?
  end

  private

  def twepic_params
    params.require(:twepic).permit(:title, :content, :image, :image_cache)
  end

  def set_twepic
    @twepic = Twepic.find(params[:id])
  end

  def login
    redirect_to new_user_path unless logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/twepics_helper.rb
module TwepicsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_twepics_path
    elsif action_name == 'edit'
      twepic_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phase32</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><%= link_to "HOME", root_path %></li>
        <li><%= link_to "つぶやき一覧", twepics_path %></li>
        <li><%= link_to "新規投稿", new_twepic_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Profile", user_path(current_user.id) %></li>
          <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_path %></li>
          <li><%= link_to "Login", new_session_path %></li>
        <% end %>
      </ul>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
    <footer>
      <p>運営会社DIVE INTO CODE株式会社</p>
      <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>
  </body>
</html>

app/views/tops/index.html.erb
<%= image_tag 'top_image.jpg', :size => '1000x500' %>
<p>写真とつぶやきをシェアしよう！</p>

app/views/twepics/_form.html.erb
<%= form_with(model: @twepic, local: true, url: choose_new_or_edit ) do |form| %>
<% if @twepic.errors.any? %>
    <div id="error_explanation">
      <h2><%= @twepic.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @twepic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="twepic_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="twepic_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image, id: :feed_image %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to '一覧画面にもどる', twepics_path %>

app/views/twepics/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @twepic, url: twepics_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>image：<%= image_tag(@twepic.image) %></p>
   <%= form.hidden_field :image_cache %>

  <p>タイトル:<%= @twepic.title %></p>
  <p>本文:<%= @twepic.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @twepic, url: new_twepic_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/twepics/edit.html.erb
<h2>ブログを編集する</h2>

  <%= render 'form' %>

app/views/twepics/index.html.erb
<h1>Twepic一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
</table>

<div class="row">
  <% @twepics.each do |twepic| %>
    <div class="col-xs-12 col-md-6">
          <p><%= twepic.user.name %>'s twepic!</p>
          <h4><%= twepic.title %></h4>
          <p><%= twepic.content %></p>
          <% if twepic.image %>
            <p><%= image_tag twepic.image %></p>
          <% end %>
          <%= link_to '詳細確認', twepic_path(twepic.id), class: "btn btn-default" %>
          <%= link_to "編集する", edit_twepic_path(twepic.id), class: "btn btn-info" %>
          <%= link_to '削除する', twepic_path(twepic.id), class: "btn btn-danger", method: :delete ,data: { confirm: '本当に削除していいですか？' }  %>
      </div>
    <% end %>
  </div>
<%= link_to '新規投稿をする', new_twepic_path, class: "btn btn-default" %>

app/views/twepics/new.html.erb
<h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/twepics/show.html.erb
<h1>ブログ詳細画面</h1>
<p>投稿ユーザー<%= @twepic.user.name %></p>
<p>タイトル: <%= @twepic.title %></p>
<p>内容: <%= @twepic.content %></p>
<% if @twepic.image %>
  <p>画像：<%= image_tag @twepic.image %></p>
<% end %>
<% unless @twepic.user_id == current_user.id %>
  <% if @favorite.present? %>
    <p><%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %></p>
  <% else %>
    <p><%= link_to 'お気に入りする', favorites_path(twepic_id: @twepic.id), method: :post, class: 'btn btn-primary' %></p>
  <% end %>
<% end %>
<%= link_to 'ブログ一覧画面にもどる', twepics_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.label :image %>
    <%= image_tag(@user.image.url) if @user.image.url %>
    <%= f.file_field :image, id: :feed_image %>
  </p>

  <p>
    <%= f.submit "Create my account" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<%= image_tag(@user.image.url) if @user.image.url %>

<h2>あなたのお気に入りしたツイート</h2>
 <% @user.favorite_twepics.each do |favorite| %>
   <p><%= favorite.user.name %>'s twepic!</p>
   <p>タイトル：<%= favorite.title %></p>
   <p>内容：<%= favorite.content %></p>
   <br>
 <% end %>